/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Advanced: typeof import('./src/components/views/Preferences/Modules/Advanced.vue')['default']
    AvatarCropper: typeof import('./src/components/utils/AvatarCropper.vue')['default']
    Casezone: typeof import('./src/components/views/Casezone/index.vue')['default']
    Customzie: typeof import('./src/components/views/Preferences/Modules/Customzie.vue')['default']
    Dialog: typeof import('./src/components/modules/Dialog.vue')['default']
    Divider: typeof import('./src/components/modules/Divider.vue')['default']
    Dropdown: typeof import('./src/components/modules/Dropdown.vue')['default']
    Edit: typeof import('./src/components/views/Preferences/Modules/Edit.vue')['default']
    EllipsisTooltip: typeof import('./src/components/utils/EllipsisTooltip.vue')['default']
    Explain: typeof import('./src/components/modules/Explain.vue')['default']
    Export: typeof import('./src/components/views/Preferences/Modules/Export.vue')['default']
    Home: typeof import('./src/components/views/Home/index.vue')['default']
    ImportFile: typeof import('./src/components/utils/ImportFile.vue')['default']
    Login: typeof import('./src/components/views/Login/index.vue')['default']
    Msg: typeof import('./src/components/modules/Msg.vue')['default']
    Notice: typeof import('./src/components/utils/Notice.vue')['default']
    Others: typeof import('./src/components/views/Preferences/Modules/Others.vue')['default']
    Pagination: typeof import('./src/components/modules/Pagination.vue')['default']
    Preferences: typeof import('./src/components/views/Preferences/index.vue')['default']
    PreferencesItem: typeof import('./src/components/modules/PreferencesItem.vue')['default']
    QuickInput: typeof import('./src/components/views/Preferences/Modules/QuickInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/views/Search/index.vue')['default']
    SiderMenu: typeof import('./src/components/utils/SiderMenu.vue')['default']
    SvgIcon: typeof import('./src/components/utils/SvgIcon.vue')['default']
    Switch: typeof import('./src/components/modules/Switch.vue')['default']
    Table: typeof import('./src/components/modules/Table.vue')['default']
    TEditor: typeof import('./src/components/utils/TEditor.vue')['default']
    Template: typeof import('./src/components/views/Template/index.vue')['default']
    TestTable: typeof import('./src/components/modules/TestTable.vue')['default']
    TrafficLight: typeof import('./src/components/utils/TrafficLight.vue')['default']
  }
}
