// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Casezone: typeof import('./src/components/views/Casezone/index.vue')['default']
    Customize: typeof import('./src/components/views/Preferences/Modules/Customize.vue')['default']
    Edit: typeof import('./src/components/views/Preferences/Modules/Edit.vue')['default']
    Editor: typeof import('./src/components/views/Preferences/Modules/Editor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Login: typeof import('./src/components/views/Login/index.vue')['default']
    Preferences: typeof import('./src/components/views/Preferences/index.vue')['default']
    Search: typeof import('./src/components/views/Search/index.vue')['default']
    SvgIcon: typeof import('./src/components/utils/SvgIcon.vue')['default']
    Template: typeof import('./src/components/views/Template/index.vue')['default']
    TrafficLight: typeof import('./src/components/utils/TrafficLight.vue')['default']
    Views: typeof import('./src/components/views/index.vue')['default']
  }
}

export { }
